export interface Emoji {
    emoji: string
    name: string
    shortcodes: string[]
}

export const COMMON_EMOJIS: Emoji[] = [
    { emoji: '😀', name: 'grinning face', shortcodes: ['smile', 'happy'] },
    { emoji: '😂', name: 'face with tears of joy', shortcodes: ['joy', 'laugh'] },
    { emoji: '🤣', name: 'rolling on the floor laughing', shortcodes: ['rofl'] },
    { emoji: '😊', name: 'smiling face with smiling eyes', shortcodes: ['blush'] },
    { emoji: '😍', name: 'smiling face with heart-eyes', shortcodes: ['heart_eyes'] },
    { emoji: '🥰', name: 'smiling face with hearts', shortcodes: ['hearts'] },
    { emoji: '😘', name: 'face blowing a kiss', shortcodes: ['kiss'] },
    { emoji: '😭', name: 'loudly crying face', shortcodes: ['cry', 'sob'] },
    { emoji: '😢', name: 'crying face', shortcodes: ['sad'] },
    { emoji: '🤔', name: 'thinking face', shortcodes: ['thinking'] },
    { emoji: '🤨', name: 'face with raised eyebrow', shortcodes: ['hmm'] },
    { emoji: '🤫', name: 'shushing face', shortcodes: ['shush'] },
    { emoji: '🫠', name: 'melting face', shortcodes: ['melting'] },
    { emoji: '🫡', name: 'saluting face', shortcodes: ['salute'] },
    { emoji: '🙄', name: 'face with rolling eyes', shortcodes: ['eye_roll'] },
    { emoji: '😬', name: 'grimacing face', shortcodes: ['grimace'] },
    { emoji: '😴', name: 'sleeping face', shortcodes: ['sleep', 'zzz'] },
    { emoji: '🤤', name: 'drooling face', shortcodes: ['drool'] },
    { emoji: '🤩', name: 'star-struck', shortcodes: ['star_eyes'] },
    { emoji: '🥳', name: 'partying face', shortcodes: ['party'] },
    { emoji: '😎', name: 'smiling face with sunglasses', shortcodes: ['cool'] },
    { emoji: '🤓', name: 'nerd face', shortcodes: ['nerd'] },
    { emoji: '🤯', name: 'exploding head', shortcodes: ['mind_blown'] },
    { emoji: '😱', name: 'face screaming in fear', shortcodes: ['scream'] },
    { emoji: '🤬', name: 'face with symbols on mouth', shortcodes: ['curse'] },
    { emoji: '🤡', name: 'clown face', shortcodes: ['clown'] },
    { emoji: '💀', name: 'skull', shortcodes: ['skull'] },
    { emoji: '🔥', name: 'fire', shortcodes: ['fire', 'lit'] },
    { emoji: '✨', name: 'sparkles', shortcodes: ['sparkles'] },
    { emoji: '⭐', name: 'star', shortcodes: ['star'] },
    { emoji: '🌟', name: 'glowing star', shortcodes: ['star2'] },
    { emoji: '💖', name: 'sparkling heart', shortcodes: ['heart', 'love'] },
    { emoji: '❤️', name: 'red heart', shortcodes: ['heart_red'] },
    { emoji: '💙', name: 'blue heart', shortcodes: ['heart_blue'] },
    { emoji: '🤝', name: 'handshake', shortcodes: ['handshake'] },
    { emoji: '👍', name: 'thumbs up', shortcodes: ['plus1', 'thumbsup'] },
    { emoji: '👎', name: 'thumbs down', shortcodes: ['minus1', 'thumbsdown'] },
    { emoji: '🙌', name: 'raising hands', shortcodes: ['raised_hands'] },
    { emoji: '👏', name: 'clapping hands', shortcodes: ['clap'] },
    { emoji: '🙏', name: 'folded hands', shortcodes: ['pray'] },
    { emoji: '✌️', name: 'victory hand', shortcodes: ['v'] },
    { emoji: '🤞', name: 'crossed fingers', shortcodes: ['fingers_crossed'] },
    { emoji: '🤟', name: 'love-you gesture', shortcodes: ['love_you'] },
    { emoji: '💪', name: 'flexed biceps', shortcodes: ['muscle'] },
    { emoji: '🤳', name: 'selfie', shortcodes: ['selfie'] },
    { emoji: '🧠', name: 'brain', shortcodes: ['brain'] },
    { emoji: '👀', name: 'eyes', shortcodes: ['eyes'] },
    { emoji: '👅', name: 'tongue', shortcodes: ['tongue'] },
    { emoji: '👄', name: 'mouth', shortcodes: ['mouth'] },
    { emoji: '🌈', name: 'rainbow', shortcodes: ['rainbow'] },
    { emoji: '☀️', name: 'sun', shortcodes: ['sun'] },
    { emoji: '🌙', name: 'moon', shortcodes: ['moon'] },
    { emoji: '⭐', name: 'star', shortcodes: ['star'] },
    { emoji: '☁️', name: 'cloud', shortcodes: ['cloud'] },
    { emoji: '🌧️', name: 'rain', shortcodes: ['rain'] },
    { emoji: '❄️', name: 'snowflake', shortcodes: ['snowflake'] },
    { emoji: '⚡', name: 'high voltage', shortcodes: ['zap'] },
    { emoji: '🌊', name: 'water wave', shortcodes: ['ocean'] },
    { emoji: '🌍', name: 'earth globe europe-africa', shortcodes: ['earth'] },
    { emoji: '🛰️', name: 'satellite', shortcodes: ['satellite'] },
    { emoji: '🚀', name: 'rocket', shortcodes: ['rocket'] },
    { emoji: '🚁', name: 'helicopter', shortcodes: ['helicopter'] },
    { emoji: '🚗', name: 'automobile', shortcodes: ['car'] },
    { emoji: '🚲', name: 'bicycle', shortcodes: ['bike'] },
    { emoji: '💻', name: 'laptop', shortcodes: ['computer'] },
    { emoji: '📱', name: 'mobile phone', shortcodes: ['phone'] },
    { emoji: '📷', name: 'camera', shortcodes: ['camera'] },
    { emoji: '🎮', name: 'video game', shortcodes: ['game'] },
    { emoji: '💡', name: 'light bulb', shortcodes: ['bulb'] },
    { emoji: '🔑', name: 'key', shortcodes: ['key'] },
    { emoji: '🔒', name: 'locked', shortcodes: ['lock'] },
    { emoji: '🔓', name: 'unlocked', shortcodes: ['unlock'] },
    { emoji: '🔨', name: 'hammer', shortcodes: ['hammer'] },
    { emoji: '🎷', name: 'saxophone', shortcodes: ['music'] },
    { emoji: '☕', name: 'hot beverage', shortcodes: ['coffee'] },
    { emoji: '🍺', name: 'beer mug', shortcodes: ['beer'] },
    { emoji: '🍕', name: 'pizza', shortcodes: ['pizza'] },
    { emoji: '🍔', name: 'hamburger', shortcodes: ['hamburger'] },
    { emoji: '🍎', name: 'red apple', shortcodes: ['apple'] },
    { emoji: '🥑', name: 'avocado', shortcodes: ['avocado'] },
    { emoji: '🌮', name: 'taco', shortcodes: ['taco'] },
    { emoji: '🍩', name: 'donut', shortcodes: ['donut'] },
    { emoji: '🍦', name: 'soft ice cream', shortcodes: ['icecream'] },
    { emoji: '🍪', name: 'cookie', shortcodes: ['cookie'] },
    { emoji: '🍭', name: 'lollipop', shortcodes: ['lollipop'] },
    { emoji: '🎁', name: 'wrapped gift', shortcodes: ['gift'] },
    { emoji: '🎈', name: 'balloon', shortcodes: ['balloon'] },
    { emoji: '🎉', name: 'party popper', shortcodes: ['tada'] },
    { emoji: '🎊', name: 'confetti ball', shortcodes: ['confetti'] },
    { emoji: '🦋', name: 'butterfly', shortcodes: ['butterfly'] },
    { emoji: '🦄', name: 'unicorn', shortcodes: ['unicorn'] },
    { emoji: '🐶', name: 'dog face', shortcodes: ['dog'] },
    { emoji: '🐱', name: 'cat face', shortcodes: ['cat'] },
    { emoji: '🐭', name: 'mouse face', shortcodes: ['mouse'] },
    { emoji: '🐹', name: 'hamster face', shortcodes: ['hamster'] },
    { emoji: '🐰', name: 'rabbit face', shortcodes: ['rabbit'] },
    { emoji: '🦊', name: 'fox face', shortcodes: ['fox'] },
    { emoji: '🐻', name: 'bear face', shortcodes: ['bear'] },
    { emoji: '🐼', name: 'panda face', shortcodes: ['panda'] },
    { emoji: '🐨', name: 'koala', shortcodes: ['koala'] },
    { emoji: '🐯', name: 'tiger face', shortcodes: ['tiger'] },
    { emoji: '🦁', name: 'lion face', shortcodes: ['lion'] },
    { emoji: '🐮', name: 'cow face', shortcodes: ['cow'] },
    { emoji: '🐷', name: 'pig face', shortcodes: ['pig'] },
    { emoji: '🐸', name: 'frog face', shortcodes: ['frog'] },
    { emoji: '🐧', name: 'penguin', shortcodes: ['penguin'] },
    { emoji: '🐦', name: 'bird', shortcodes: ['bird'] },
    { emoji: '🐤', name: 'baby chick', shortcodes: ['chick'] },
    { emoji: '🦆', name: 'duck', shortcodes: ['duck'] },
    { emoji: '🦅', name: 'eagle', shortcodes: ['eagle'] },
    { emoji: '🦉', name: 'owl', shortcodes: ['owl'] },
    { emoji: '🦇', name: 'bat', shortcodes: ['bat'] },
    { emoji: '🐺', name: 'wolf face', shortcodes: ['wolf'] },
    { emoji: '🦖', name: 't-rex', shortcodes: ['t-rex'] },
    { emoji: '🐳', name: 'spouting whale', shortcodes: ['whale'] },
    { emoji: '🐬', name: 'dolphin', shortcodes: ['dolphin'] },
    { emoji: '🐟', name: 'fish', shortcodes: ['fish'] },
    { emoji: '🐠', name: 'tropical fish', shortcodes: ['tropical_fish'] },
    { emoji: '🐡', name: 'blowfish', shortcodes: ['blowfish'] },
    { emoji: '🦈', name: 'shark', shortcodes: ['shark'] },
    { emoji: '🐙', name: 'octopus', shortcodes: ['octopus'] },
    { emoji: '🐚', name: 'spiral shell', shortcodes: ['shell'] },
    { emoji: '🦀', name: 'crab', shortcodes: ['crab'] },
    { emoji: '🦐', name: 'shrimp', shortcodes: ['shrimp'] },
    { emoji: '🦑', name: 'squid', shortcodes: ['squid'] },
    { emoji: '🐌', name: 'snail', shortcodes: ['snail'] },
    { emoji: '🐛', name: 'bug', shortcodes: ['bug'] },
    { emoji: '🐜', name: 'ant', shortcodes: ['ant'] },
    { emoji: '🐝', name: 'honeybee', shortcodes: ['bee'] },
    { emoji: '🐞', name: 'lady beetle', shortcodes: ['ladybug'] },
    { emoji: '🕷️', name: 'spider', shortcodes: ['spider'] },
    { emoji: '🕸️', name: 'spider web', shortcodes: ['spider_web'] },
    { emoji: '🦂', name: 'scorpion', shortcodes: ['scorpion'] },
    { emoji: '🦟', name: 'mosquito', shortcodes: ['mosquito'] },
    { emoji: '🦠', name: 'microbe', shortcodes: ['microbe'] },
    { emoji: '💐', name: 'bouquet', shortcodes: ['flowers'] },
    { emoji: '🌸', name: 'cherry blossom', shortcodes: ['cherry_blossom'] },
    { emoji: '💮', name: 'white flower', shortcodes: ['flower'] },
    { emoji: '🌹', name: 'rose', shortcodes: ['rose'] },
    { emoji: '🥀', name: 'wilted flower', shortcodes: ['wilted_flower'] },
    { emoji: '🌺', name: 'hibiscus', shortcodes: ['hibiscus'] },
    { emoji: '🌻', name: 'sunflower', shortcodes: ['sunflower'] },
    { emoji: '🌼', name: 'blossom', shortcodes: ['blossom'] },
    { emoji: '🌷', name: 'tulip', shortcodes: ['tulip'] },
    { emoji: '🌱', name: 'seedling', shortcodes: ['seedling'] },
    { emoji: '🌲', name: 'evergreen tree', shortcodes: ['evergreen_tree'] },
    { emoji: '🌳', name: 'deciduous tree', shortcodes: ['deciduous_tree'] },
    { emoji: '🌴', name: 'palm tree', shortcodes: ['palm_tree'] },
    { emoji: '🌵', name: 'cactus', shortcodes: ['cactus'] },
    { emoji: '🌿', name: 'herb', shortcodes: ['herb'] },
    { emoji: '🍀', name: 'four leaf clover', shortcodes: ['clover'] },
    { emoji: '🍁', name: 'maple leaf', shortcodes: ['maple_leaf'] },
    { emoji: '🍂', name: 'fallen leaf', shortcodes: ['fallen_leaf'] },
    { emoji: '🍃', name: 'leaf fluttering in wind', shortcodes: ['leaves'] },
    { emoji: '🍄', name: 'mushroom', shortcodes: ['mushroom'] },
    { emoji: '🌰', name: 'chestnut', shortcodes: ['chestnut'] },
    { emoji: '🦀', name: 'crab', shortcodes: ['crab'] },
    { emoji: '🦐', name: 'shrimp', shortcodes: ['shrimp'] },
    { emoji: '🦑', name: 'squid', shortcodes: ['squid'] },
]
